<?php
return [
    'cssVars' => [
        '--intro-blackout-ms' => '1500ms',
        '--intro-bg-fade-ms' => '3100ms',
        '--logo-reveal-ms' => '3100ms',
        '--logo-initial-opacity' => '0.2',
        '--logo-initial-blur' => '80px',
        '--logo-initial-brightness' => '0.85',
        '--logo-initial-scale' => '2',
        '--logo-move-duration-ms' => '2050ms',
        '--logo-move-delay-ms' => '1500ms',
        '--logo-arc-x' => '0.65',
        '--logo-arc-dy' => '60px',
        '--grid-hue-duration-ms' => '2500ms',
        '--square-shake-duration-ms' => '1500ms',
        '--square-shake-amp' => '14px',
        '--square-scale-end' => '1.25',
        '--orb-float-duration-s' => '8s',
        '--grid-float-duration-s' => '6s',
        '--eyebrow-size' => '1rem',
        '--services-fade-delay-ms' => '1000ms',
        '--neon' => '#00FFA6',
        '--square-green-rgba' => '0,255,150',
        '--logo-ease' => 'cubic-bezier(.2,.8,.2,1)',
    ],
    'behaviors' => [
        'reactHover' => true,
        'reactContact' => true,
        'heroMask' => true,
        'floatingGrid' => false,
        'pageVibration' => 0,
        'hybercube' => true,
        'chatDock' => true,
    ],
    'preset' => null,
    'meta' => [
        'updated_at' => gmdate('c'),
        'updated_by' => 'Bootstrap',
    ],
    'branding' => [
        'navEmblemUrl' => 'assets/logotp.png',
        'logoUrl' => 'assets/logotp.png',
        'faviconUrl' => 'assets/logotp.png',
        'heroLogoUrl' => 'assets/logo.png',
        'heroGridBackground' => 'assets/logo.png',
    ],
    'content' => [
        'heroHighlight' => 'Yksilöllinen',
        'heroEyebrow' => 'Yksilöllinen sovelluskehitys & kyberturva',
        'heroTitle' => 'Yksilöllisten sovellusten koodaaminen juuri yrityksenne tarpeisiin.',
        'heroTitleHtml' => "<span class=\"hero-title-line\">Yksilöllisten</span><span class=\"hero-title-line\">Sovellusten</span><span class=\"hero-title-line\">Valmistaminen</span><span class=\"hero-title-line hero-title-subline\">- Juuri yrityksenne tarpeisiin.</span>",
        'heroSubtitle' => 'Sovelluksia <strong>kaikille alustoille</strong> – mobiilista työpöydälle. Kyberturva sisäänrakennettuna jokaisessa ratkaisussa.',
        'serviceTagline' => '"Koodia, joka kantaa – tänään ja huomenna."',
        'serviceIntro' => 'Toimitamme pienen toimivan version nopeasti – kasvatamme tarpeen mukaan.',
    ],
    'shortener' => [
        'baseUrl' => 'https://anomfin.fi/?s=',
        'maxLength' => 4,
        'enforceHttps' => true,
        'autoPurgeDays' => 365,
        'redirectStatus' => 302,
        'utmCampaign' => 'anomfin-hyperlaunch',
    ],
    'integrations' => [
        'chat' => [
            'enabled' => true,
            'provider' => 'openai',
            'endpoint' => 'api/chat.php',
            'model' => 'gpt-4.1-mini',
            'temperature' => 0.6,
            'systemPrompt' => 'Toimi AnomFIN HyperLaunch -neuvojana. Vastaa suomeksi, ole asiantunteva, ystävällinen ja ytimekäs. Suosittele palveluitamme yritysasiakkaille.',
            'greeting' => 'Tervetuloa HyperLaunch-chattiin – luksissa, kyberturvassa ilmoittelussa – kysy rohkeasti.',
            'followup' => 'Olen AnomFIN chatBot, mitäs kaipailette?',
            'apiKey' => '',
            'avatarUrl' => 'assets/logotp.png',
        ],
    ],
];
